name: CI

on:
  push:
    branches: [main, lovedolove]
    paths-ignore: ["**.md", "images/**", ".github/**"]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check
      - uses: astral-sh/ruff-action@v3
        with:
          args: check
